/**
 * Antigravity Optimized Harness - Structured Handoff Protocol
 * Transfers strictly compact, structured, factual findings between agents without raw transcripts.
 */

import { StructuredHandoff, AgentRole } from './types.js';

export class StructuredHandoffManager {
  public createHandoff(
    role: AgentRole,
    objective: string,
    rawOutput: string,
    filesChanged: string[] = [],
    testsRun: string[] = []
  ): StructuredHandoff {
    const lines = rawOutput.split('\n').map(l => l.trim()).filter(Boolean);
    const findings: string[] = [];
    const decisions: string[] = [];

    for (const line of lines) {
      if (line.startsWith('- ') || line.startsWith('* ')) {
        const item = line.replace(/^[-*]\s+/, '');
        if (item.toLowerCase().includes('decision') || item.toLowerCase().includes('chose') || item.toLowerCase().includes('implemented')) {
          decisions.push(item);
        } else if (findings.length < 5) {
          findings.push(item);
        }
      }
    }

    if (findings.length === 0) {
      findings.push(rawOutput.slice(0, 200).replace(/\n/g, ' '));
    }

    return {
      objective,
      status: 'completed',
      findings,
      evidence: [`Generated by ${role} at ${new Date().toISOString()}`],
      decisions: decisions.length > 0 ? decisions : ['Applied default optimal pattern'],
      assumptions: ['Standard TypeScript/Node runtime constraints'],
      filesChanged,
      testsRun,
      unresolved: [],
      confidence: 0.95,
      timestamp: Date.now(),
      producedByRole: role
    };
  }

  public formatForNextAgent(handoff: StructuredHandoff): string {
    return [
      `[HANDOFF from ${handoff.producedByRole.toUpperCase()}]`,
      `Objective: ${handoff.objective}`,
      `Status: ${handoff.status.toUpperCase()} (Confidence: ${Math.round(handoff.confidence * 100)}%)`,
      `Decisions:`,
      ...handoff.decisions.map(d => `  - ${d}`),
      `Key Findings:`,
      ...handoff.findings.map(f => `  - ${f}`),
      handoff.filesChanged.length > 0 ? `Files Changed: ${handoff.filesChanged.join(', ')}` : '',
      handoff.unresolved.length > 0 ? `Unresolved: ${handoff.unresolved.join(', ')}` : ''
    ].filter(Boolean).join('\n');
  }
}

export const structuredHandoffManager = new StructuredHandoffManager();
